language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update
  - composer --version

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit -c tests/phpunit.xml.dist
