name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * 6'
jobs:
  tests:
    name: Test against php ${{ matrix.php-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php-version: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer, phpunit
          coverage: none
        env:
          fail-fast: true
      - name: Install dependencies
        run: composer install -n
      - name: Run test suite
        run: vendor/bin/phpunit
